# TODO: 
1. import of hoinetx in first cell.

In [9]:
import sys

import numpy as np
import matplotlib.pyplot as plt

sys.path.append("..")
from hoinetx.core.hypergraph import Hypergraph
from hoinetx.linalg.linalg import compute_multiorder_laplacian, laplacian_matrices_all_orders
from hoinetx.dynamics.synch import higher_order_MSF

from scipy.linalg import eigh

np.random.seed(123)

In [7]:
# definition of the higher-order network
edge_list = [[0,7],[1,2],[1,7],[2,7],[3,7],[4,7],[5,7],[6,7],[1,2,7],[4,5,6],[4,5,7],[4,6,7],[5,6,7],[4,5,6,7]]
hypergraph = Hypergraph(edge_list)

N = hypergraph.num_nodes()

# definition of the coupling coefficients, i.e., the strength of each order of interaction 
sigmas = [1,1,1]

## Analysis of the multiorder Laplacian matrix
Here we show how to analyze the multiorder Laplacian matrix defined for synchronization in higher-order networks.

Source: 

Lucas M., Cencetti G., Battiston F., _Multiorder Laplacian for synchronization in higher-order networks_, Physical Review Research *2*, 033410 (2020)


In [3]:
# We can compute the Laplacian matrix for the different orders of interaction with
laplacians = laplacian_matrices_all_orders(hypergraph)

# for instance, the Laplacian matrix of order 2, i.e., the Laplacian matrix for three-body interactions, is given by
print(laplacians[2].todense())


[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2. -1.  0.  0.  0.  0. -1.]
 [ 0. -1.  2.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  6. -2. -2. -2.]
 [ 0.  0.  0.  0. -2.  6. -2. -2.]
 [ 0.  0.  0.  0. -2. -2.  6. -2.]
 [ 0. -1. -1.  0. -2. -2. -2.  8.]]


In [15]:
# We can compute the multiorder Laplacian with
multiorder_laplacian = compute_multiorder_laplacian(hypergraph,sigmas)

print(multiorder_laplacian.toarray().round(3))

[[ 0.5    0.     0.     0.     0.     0.     0.    -0.5  ]
 [ 0.     2.067 -1.033  0.     0.     0.     0.    -1.033]
 [ 0.    -1.033  2.067  0.     0.     0.     0.    -1.033]
 [ 0.     0.     0.     0.5    0.     0.     0.    -0.5  ]
 [ 0.     0.     0.     0.     9.7   -3.067 -3.067 -3.567]
 [ 0.     0.     0.     0.    -3.067  9.7   -3.067 -3.567]
 [ 0.     0.     0.     0.    -3.067 -3.067  9.7   -3.567]
 [-0.5   -1.033 -1.033 -0.5   -3.567 -3.567 -3.567 13.767]]


In [13]:
# The stability of a system of Kuramoto oscillators depends on the spectrum of the multiorder Laplacian
spectrum = eigh(multiorder_laplacian.toarray(), eigvals_only=True)

print(spectrum)

[1.36175793e-16 5.00000000e-01 6.05839850e-01 1.44725527e+00
 3.10000000e+00 1.27666667e+01 1.27666667e+01 1.68135715e+01]
